export const SITE_CONTENT = {
  siteMetadata: {
    title: "香港使用手冊 | 一站式生活服務平台",
    description:
      "專為來港工作、讀書及移居人士打造的一站式生活服務平台。按小時預約本地伴行導師，協助辦理銀行開戶、陪同睇樓、尋覓美食及熟悉社區生活。",
    currency: "HKD",
    languages: ["繁體中文", "简体中文", "English"],
  },
  navigation: {
    logoText: "香港使用手冊",
    links: [
      { label: "首頁", url: "/" },
      { label: "找生活導師", url: "/profiles" },
      { label: "使用指南", url: "/#how-it-works" },
      { label: "加入我們成為導師", url: "/join" },
    ],
    ctaButton: { label: "立即預約服務", url: "/profiles" },
  },
  homePage: {
    heroSection: {
      title: "翻開《香港使用手冊》，解鎖你的港式生活。",
      subtitle:
        "剛來香港手足無措？一站式生活服務平台幫到你。按小時預約通過認證的本地「生活導師」，陪你搞定銀行開戶、身份證辦理、線下睇樓、餐廳探店，讓你光速融入新生活。",
      primaryCTA: { label: "瀏覽生活導師", url: "/profiles" },
      secondaryCTA: { label: "手冊使用說明", url: "#how-it-works" },
      stats: [
        { value: "1,200+", label: "已解鎖伴行服務" },
        { value: "4.9/5", label: "用戶滿意度" },
        { value: "100%", label: "導師實名認證" },
      ],
    },
    servicesCategories: {
      title: "一站式服務範疇：你需要哪種協助？",
      description: "按需選擇你的專屬伴行服務，我們的導師精通粵語、普通話及英語。",
      categories: [
        {
          id: "admin-banking",
          title: "行政與銀行開戶",
          description:
            "陪同前往本地銀行、辦理香港身份證、電話卡及八達通，避免因語言或流程不熟而碰壁。",
        },
        {
          id: "housing-tours",
          title: "線下租房睇樓陪同",
          description:
            "不孤單面對中介。本地導師陪你實地看房，幫你留意周邊環境與租約細節，拒絕踩坑。",
        },
        {
          id: "social-food",
          title: "香港探店與生活融入",
          description:
            "想去茶餐廳普通話點餐怕尷尬？想去西九龍或隱蔽酒吧？找個本地搭子陪你邊吃邊聊。",
        },
        {
          id: "campus-study",
          title: "校園適應與學業嚮導",
          description:
            "適合非本地新生。學長學姐帶你熟悉港大、科大等校園，購買二手教科書，傳授選課攻略。",
        },
      ],
    },
    howItWorks: {
      id: "how-it-works",
      title: "平台使用指南（三步開啟）",
      steps: [
        {
          stepNumber: "1",
          title: "自選專屬「導師」",
          description: "根據導師的擅長領域、語言（粵語/普通話/英文）以及時薪進行篩選。",
        },
        {
          stepNumber: "2",
          title: "安全預約與支付",
          description:
            "選擇日期、所需小時數及見面地點。支持信用卡、轉數快 (FPS) 或 PayMe 安全線上預付。",
        },
        {
          stepNumber: "3",
          title: "線下見面 輕鬆解鎖",
          description:
            "在約定地點與導師匯合。平台會託管資金，待服務結束並確認無誤後，才會撥款給導師。",
        },
      ],
    },
    trustSection: {
      title: "一站式安全防護機制",
      points: [
        {
          title: "100% 身份審查",
          text: "所有生活導師必須上傳身份證件及進行背景真人核驗。",
        },
        {
          title: "擔保交易資金安全",
          text: "費用先由平台託管，服務完成後才結算，保障雙方權益。",
        },
        {
          title: "客服隨時在線",
          text: "伴行過程中如有任何突發情況，平台客服實時為你提供支援。",
        },
      ],
    },
    socialProof: {
      title: "香港新生活，用戶這樣說",
      cards: [
        {
          name: "Lily · 研究生",
          quote: "第一次辦銀行開戶被拒好幾次，導師陪同後一次完成，還幫我整理文件清單。",
        },
        {
          name: "Eric · 新來港上班族",
          quote: "看房最怕資訊不對等，導師會提醒租約細節，真的省下很多時間和踩雷成本。",
        },
        {
          name: "Mia · 交換生",
          quote: "有人帶路吃地道小店和熟悉社區，短短兩星期就感覺自己像半個本地人。",
        },
      ],
    },
    faq: {
      title: "常見問題",
      items: [
        {
          q: "導師是否通過身份驗證？",
          a: "所有導師都需完成實名驗證及背景資料審核，並遵守平台服務守則。",
        },
        {
          q: "可以使用哪些語言溝通？",
          a: "平台支援粵語、普通話及英語，你可以按語言能力篩選導師。",
        },
        {
          q: "服務如何收費？",
          a: "以小時計費，預約前會清楚顯示價格與時長，統一以 HKD 結算。",
        },
      ],
    },
  },
  profilesPage: {
    title: "挑選你的生活導師",
    filters: {
      languages: ["粵語", "普通話", "英語"],
      specialties: ["銀行行政", "租房睇樓", "美食社交", "校園嚮導"],
      priceRange: ["HKD 100-150/小時", "HKD 151-200/小時", "HKD 201+/小時"],
    },
    profilesList: [
      {
        id: "comp-001",
        name: "Christy L.",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
        tagline: "港大畢業 • 銀行開戶達人 • 精通普通話/英語",
        hourlyRate: 150,
        rating: 4.9,
        reviewsCount: 28,
        languages: ["粵語", "普通話", "英語"],
        specialties: ["銀行行政", "校園嚮導", "美食社交"],
        bio: "哈囉！我來香港讀書工作已經6年了。非常理解新同學剛來的迷茫，我可以陪你去中環或旺角的銀行高效開戶，避開排隊冤枉路！",
      },
      {
        id: "comp-002",
        name: "Marcus W.",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
        tagline: "香港土生土長 • 睇樓排雷專家 • 流利英語",
        hourlyRate: 180,
        rating: 5.0,
        reviewsCount: 14,
        languages: ["粵語", "英語"],
        specialties: ["租房睇樓", "美食社交"],
        bio: "地道香港人，對九龍和港島的租房市場非常熟悉。陪新來港人才看房睇樓，幫你跟地產中介溝通、檢查屋況，看完順便帶你吃地道茶餐廳！",
      },
  {
    id: "comp-012",
    name: "Marcus T.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    tagline: "中大商科生 • 數碼通/1010辦卡達人 • 粵英流利",
    hourlyRate: 120,
    rating: 4.8,
    reviewsCount: 19,
    languages: ["粵語", "英語", "普通話"],
    specialties: ["電訊上網", "交通指引", "電子支付設定"],
    bio: "新來港最頭痛的就是辦電話卡和各種電子錢包設定。我會帶你對比各家電訊商隱藏優惠，1小時內搞定高性價比電話卡與八達通綁定！",
  },
  {
    id: "comp-003",
    name: "Serena W.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    tagline: "理大設計系 • 旺角/深水埗平價生活圈嚮導",
    hourlyRate: 140,
    rating: 4.9,
    reviewsCount: 34,
    languages: ["粵語", "普通話"],
    specialties: ["生活採購", "二手家具淘寶", "平價美食"],
    bio: "剛租好房子空空如也？別去連鎖店買貴了！我帶你逛深水埗和網上二手社群，用最預算內的方式添置全屋生活用品，順便帶你吃道地街坊小吃。",
  },
  {
    id: "comp-004",
    name: "Kelvin C.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    tagline: "科大工程碩士 • 租房避坑專家 • 廣東話日常對話",
    hourlyRate: 160,
    rating: 4.7,
    reviewsCount: 15,
    languages: ["粵語", "普通話", "英語"],
    specialties: ["租房陪驗", "社區安全評估", "粵語糾音"],
    bio: "香港租房合約有很多隱藏條款（如生約死約、維修權責）。我能陪同你看房驗樓，幫你跟房東/中介用粵語精準爭取權益，拒當冤大頭！",
  },
  {
    id: "comp-005",
    name: "Elena K.",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
    tagline: "留港法籍港大生 • 港島西區文化融入 • 純英對話",
    hourlyRate: 180,
    rating: 5.0,
    reviewsCount: 42,
    languages: ["英語", "法語"],
    specialties: ["全英社交", "西營盤/中環街區", "國際生融入"],
    bio: "想快速提升英語聽力並融入國際化圈子嗎？我可以陪你在西營盤的咖啡廳或中環蘇豪區聊天，帶你熟悉香港的多元文化與西方社交禮儀。",
  },
  {
    id: "comp-006",
    name: "阿豪 (Anson)",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7",
    tagline: "土生土長九龍人 • 廣東話日常急救 • 街頭文化愛好者",
    hourlyRate: 130,
    rating: 4.9,
    reviewsCount: 56,
    languages: ["粵語", "普通話"],
    specialties: ["道地粵語", "茶餐廳點餐指南", "紅Van搭乘教學"],
    bio: "聽不懂街市阿伯講什麼？不敢自己進茶餐廳點餐？別怕！我用最實戰的方式教你常用的生活粵語、香港潮語，讓你一星期內聽懂九成日常對話！",
  },
  {
    id: "comp-007",
    name: "Tiffany M.",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    tagline: "浸大傳理系 • 香港各大文青打卡點/展覽嚮導",
    hourlyRate: 150,
    rating: 4.8,
    reviewsCount: 22,
    languages: ["粵語", "普通話", "英語"],
    specialties: ["M+ & 故宮拍照", "文青路線規劃", "街頭攝影"],
    bio: "週末不知道去哪裡？我帶你深度遊西九文化區、大館、PMQ，幫你拍出最有港風文青感的高質感照片，快速建立你在香港的美好生活圈！",
  },
  {
    id: "comp-008",
    name: "Jackson L.",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61",
    tagline: "城大政管畢業 • 身份簽注與身份證辦理達人",
    hourlyRate: 140,
    rating: 4.6,
    reviewsCount: 18,
    languages: ["粵語", "普通話"],
    specialties: ["人事登記處陪辦", "政府表格填寫", "公共交通規劃"],
    bio: "辦理香港身份證預約不到？各種表格不知道怎麼填？我可以協助你準備好所有證明文件，陪同前往入境處辦理，省去重複排隊補件的痛苦。",
  },
  {
    id: "comp-009",
    name: "Vicky S.",
    avatarUrl: "https://images.unsplash.com/photo-1554151228-14d9def656e4",
    tagline: "瑜伽教練 • 香港行山/郊野公園秘境探索",
    hourlyRate: 160,
    rating: 4.9,
    reviewsCount: 29,
    languages: ["普通話", "英語", "粵語"],
    specialties: ["戶外徒步", "大自然療癒", "健康生活社交"],
    bio: "香港不只有高樓大廈，還有世界級的行山徑。不管你是想挑戰龍脊還是輕鬆走麥理浩徑，我都能當你的安全嚮導，一起呼吸新鮮空氣、結交新朋友！",
  },
  {
    id: "comp-010",
    name: "Derek W.",
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce",
    tagline: "前4A廣告公司職員 • 港式職場文化與商務粵語",
    hourlyRate: 200,
    rating: 5.0,
    reviewsCount: 41,
    languages: ["粵語", "英語"],
    specialties: ["商務粵語", "職場社交規矩", "面試模擬"],
    bio: "準備留在香港實習或工作？港式職場有獨特的 Email 寫法和茶水間政治。我會透過一對一模擬與下午茶對話，幫你打通香港職場的社交任督二脈。",
  },
  {
    id: "comp-011",
    name: "Chloe Ng",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    tagline: "中醫藥膳愛好者 • 街市買菜與港式煲湯秘籍傳授",
    hourlyRate: 130,
    rating: 4.7,
    reviewsCount: 12,
    languages: ["粵語", "普通話"],
    specialties: ["本地街市實戰", "港式煲湯教學", "廣東話買菜口訣"],
    bio: "香港天氣潮濕，學會煲湯是生存技能！帶你走進最道地的灣仔/旺角街市，教你用粵語跟菜販、肉販打交道，手把手教你認藥材，熬出第一鍋去濕靚湯！",
  }
    ],
  },
  bookingAndPaymentPage: {
    title: "預約生活服務",
    formFields: {
      companionSelection: "已選生活導師",
      datePickerLabel: "選擇日期",
      timePickerLabel: "開始時間",
      durationLabel: "預計時數 (小時)",
      meetingLocationLabel: "約定見面地點 (例如：中環地鐵站A出口)",
      notesLabel: "你需要導師協助的具體事項？（請詳細填寫）",
    },
    checkoutSummary: {
      title: "費用明細",
      hourlyRateLabel: "導師時薪",
      platformFeeLabel: "平台服務費 (10%)",
      totalLabel: "總計支付金額",
      paymentMethods: ["信用卡", "轉數快 (FPS)", "PayMe", "Apple Pay"],
    },
    submitLabel: "確認預約並前往支付",
  },
  paymentTestPage: {
    title: "信用卡支付（測試環境）",
    subtitle: "此頁面僅供開發與驗收測試，不會向銀行發送真實扣款。",
    testModeBadge: "TEST MODE",
    cardSectionTitle: "信用卡資料",
    fields: {
      cardholderName: "持卡人姓名",
      cardNumber: "卡號",
      expiry: "到期日 (MM/YY)",
      cvc: "安全碼 (CVC)",
    },
    testCardsTitle: "測試卡號參考（Stripe 測試環境）",
    testCards: [
      { label: "成功付款", number: "4242 4242 4242 4242", note: "任意未來到期日與 CVC" },
      { label: "需要驗證 (3DS)", number: "4000 0025 0000 3155", note: "模擬額外驗證流程" },
      { label: "付款被拒", number: "4000 0000 0000 0002", note: "模擬卡片被拒" },
    ],
    payButtonLabel: "模擬支付 HKD {amount}",
    processingLabel: "處理中…",
    backToBookingLabel: "返回修改預約",
    escrowNote: "款項將由平台託管，服務完成確認後才結算給導師。",
  },
  bookingSuccessPage: {
    title: "預約已確認",
    subtitle: "你的付款（測試）已成功記錄，導師將在約定時間與你匯合。",
    referenceLabel: "預約編號",
    viewProfilesLabel: "返回導師列表",
    homeLabel: "返回首頁",
  },
  footer: {
    copyright: "© 2026 香港使用手冊. 一站式生活服務平台. 版權所有.",
    links: ["服務條款", "隱私政策", "安全指引", "聯絡客服"],
  },
} as const;
